# Generated by Django 4.0.3 on 2022-03-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0002_category_location_alter_image_options_image_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
